# the thing you use to run python file scripts
py := python


# Questions
quest:
	$(py) questions.py

# an example
ex:
	$(py) main.py 0

# running the same example with the verbose option
ex_verbose:
	$(py) main.py 1
